export const FETCH_CITIES = "FETCH_CITIES";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CLUBS = "FETCH_CLUBS";
export const SET_CURRENT_CITY = "SET_CURRENT_CITY";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";